
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed2;

	private global::Gtk.RadioButton radiobutton3;

	private global::Gtk.RadioButton radiobutton4;

	private global::Gtk.RadioButton radiobutton5;

	private global::Gtk.RadioButton radiobutton6;

	private global::Gtk.Button button3;

	private global::Gtk.Label label2;

	private global::Gtk.Image image1;

	private global::Gtk.Image image2;

	private global::Gtk.Image image3;

	private global::Gtk.Image image4;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed2 = new global::Gtk.Fixed();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.radiobutton3 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("УТ1"));
		this.radiobutton3.CanFocus = true;
		this.radiobutton3.Name = "radiobutton3";
		this.radiobutton3.DrawIndicator = true;
		this.radiobutton3.UseUnderline = true;
		this.radiobutton3.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.fixed2.Add(this.radiobutton3);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.radiobutton3]));
		w1.X = 30;
		w1.Y = 58;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.radiobutton4 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Интер"));
		this.radiobutton4.CanFocus = true;
		this.radiobutton4.Name = "radiobutton4";
		this.radiobutton4.DrawIndicator = true;
		this.radiobutton4.UseUnderline = true;
		this.radiobutton4.Group = this.radiobutton3.Group;
		this.fixed2.Add(this.radiobutton4);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.radiobutton4]));
		w2.X = 29;
		w2.Y = 89;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.radiobutton5 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("1+1"));
		this.radiobutton5.CanFocus = true;
		this.radiobutton5.Name = "radiobutton5";
		this.radiobutton5.DrawIndicator = true;
		this.radiobutton5.UseUnderline = true;
		this.radiobutton5.Group = this.radiobutton3.Group;
		this.fixed2.Add(this.radiobutton5);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.radiobutton5]));
		w3.X = 29;
		w3.Y = 121;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.radiobutton6 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("СТБ"));
		this.radiobutton6.CanFocus = true;
		this.radiobutton6.Name = "radiobutton6";
		this.radiobutton6.DrawIndicator = true;
		this.radiobutton6.UseUnderline = true;
		this.radiobutton6.Group = this.radiobutton3.Group;
		this.fixed2.Add(this.radiobutton6);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.radiobutton6]));
		w4.X = 30;
		w4.Y = 151;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("Выключить");
		this.fixed2.Add(this.button3);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.button3]));
		w5.X = 149;
		w5.Y = 212;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Выберите теливизионный канал");
		this.fixed2.Add(this.label2);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label2]));
		w6.X = 84;
		w6.Y = 15;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.image1 = new global::Gtk.Image();
		this.image1.Name = "image1";
		this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("_2_TV.ut.png");
		this.fixed2.Add(this.image1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.image1]));
		w7.X = 191;
		w7.Y = 81;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.image2 = new global::Gtk.Image();
		this.image2.Name = "image2";
		this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("_2_TV.inter.png");
		this.fixed2.Add(this.image2);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.image2]));
		w8.X = 193;
		w8.Y = 52;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.image3 = new global::Gtk.Image();
		this.image3.Name = "image3";
		this.image3.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("_2_TV.plus.png");
		this.fixed2.Add(this.image3);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.image3]));
		w9.X = 194;
		w9.Y = 55;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.image4 = new global::Gtk.Image();
		this.image4.Name = "image4";
		this.image4.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("_2_TV.stb.png");
		this.fixed2.Add(this.image4);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.image4]));
		w10.X = 214;
		w10.Y = 70;
		this.Add(this.fixed2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 507;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.radiobutton3.Clicked += new global::System.EventHandler(this.setut);
		this.radiobutton4.GroupChanged += new global::System.EventHandler(this.setinter);
		this.radiobutton4.Clicked += new global::System.EventHandler(this.setinter);
		this.radiobutton5.Clicked += new global::System.EventHandler(this.setplus);
		this.radiobutton6.Clicked += new global::System.EventHandler(this.setstb);
		this.button3.Clicked += new global::System.EventHandler(this.killapp);
	}
}
